[package]
name = "shinkai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
matrix = { git = "https://github.com/Ryo-sunken/matrix-rs.git", branch = "main" }